# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import producer_consumer_pb2 as producer__consumer__pb2
import unified_planning_pb2 as unified__planning__pb2


class UnifiedPlanningProducerConsumerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.produce = channel.unary_unary(
                '/UnifiedPlanningProducerConsumer/produce',
                request_serializer=producer__consumer__pb2.Empty.SerializeToString,
                response_deserializer=unified__planning__pb2.PlanRequest.FromString,
                )
        self.consume = channel.unary_unary(
                '/UnifiedPlanningProducerConsumer/consume',
                request_serializer=unified__planning__pb2.PlanGenerationResult.SerializeToString,
                response_deserializer=producer__consumer__pb2.Empty.FromString,
                )


class UnifiedPlanningProducerConsumerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def produce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def consume(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UnifiedPlanningProducerConsumerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'produce': grpc.unary_unary_rpc_method_handler(
                    servicer.produce,
                    request_deserializer=producer__consumer__pb2.Empty.FromString,
                    response_serializer=unified__planning__pb2.PlanRequest.SerializeToString,
            ),
            'consume': grpc.unary_unary_rpc_method_handler(
                    servicer.consume,
                    request_deserializer=unified__planning__pb2.PlanGenerationResult.FromString,
                    response_serializer=producer__consumer__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UnifiedPlanningProducerConsumer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UnifiedPlanningProducerConsumer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def produce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UnifiedPlanningProducerConsumer/produce',
            producer__consumer__pb2.Empty.SerializeToString,
            unified__planning__pb2.PlanRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def consume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UnifiedPlanningProducerConsumer/consume',
            unified__planning__pb2.PlanGenerationResult.SerializeToString,
            producer__consumer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
